DATABASE_INSERT_STRING = """
<nameValuePair>
  <name>DatabaseServer</name>
    <value>
      <string>localhost</string>
    </value>
</nameValuePair>
<nameValuePair>
  <name>DatabaseUserName</name>
    <value>
      <string>ben</string>
    </value>
</nameValuePair>
<nameValuePair>
  <name>Database</name>
  <value>
    <string>fjsp</string>
  </value>
</nameValuePair>
<nameValuePair>
  <name>DatabasePassword</name>
    <value>
      <string>password</string>
    </value>
</nameValuePair>
<nameValuePair>
  <name>DatabasePort</name>
  <value>
    <string>5432</string>
  </value>
</nameValuePair>
"""